### ISSUE TITLE
How to support/contribute?

### ISSUE THREAD

**Issue by enzingerm** [xmm7360/reversing#1]
Hello James, I really appreciate the efforts you put into getting the L850-GL modem to work under Linux. As I own a T495 which seems to not have the M.2 USB lanes routed, I think I depend on a working PCIe driver to get the modem working on my machine.
I don't know if its possible to support you with your work considering my very limited to non-existant knowledge of driver internals and reverse engineering (though I'd be keen to learn). Thus I'd like to ask you if you could make use of any help regarding
- Testing
- Actual development
- help in other areas

**Comment by abrasive** [comment]
I'm not sure what wants doing next, but here's a start:

https://github.com/xmm7360/xmm7360-pci

As the README says, raw IP support will follow very shortly, so in terms of raw functionality it's basically got everything I need.

But, there is a *lot* of honing to do. Power management is absent, there's no integration with ModemManager or anything, the RPC interface stuff is filthy and needs a lot of love.

**Comment by kkarhan** [comment]
Maybe the NetBSD driver will give us a hint?
https://github.com/xmm7360/reversing/issues/2

**Comment by tgxn** [comment]
closing this as @enzingerm has done some contributing now :)
